// Generated by CoffeeScript 1.10.0
(function() {
  var isTouch, mouseManuallyDisabled, relMouseCoordsWithin,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  mouseManuallyDisabled = false;

  isTouch = function() {
    return mouseManuallyDisabled || indexOf.call(window, 'ontouchstart') >= 0 || navigator.maxTouchPoints;
  };

  relMouseCoordsWithin = function(event, canvas, x, y, width, height) {
    var canvasX, canvasY, changedTouches, currentElement, firstTouch, totalOffsetX, totalOffsetY, touches;
    totalOffsetX = 0;
    totalOffsetY = 0;
    canvasX = 0;
    canvasY = 0;
    currentElement = canvas;
    totalOffsetX += currentElement.offsetLeft - currentElement.scrollLeft;
    totalOffsetY += currentElement.offsetTop - currentElement.scrollTop;
    while (currentElement = currentElement.offsetParent) {
      totalOffsetX += currentElement.offsetLeft - currentElement.scrollLeft;
      totalOffsetY += currentElement.offsetTop - currentElement.scrollTop;
    }
    touches = event.touches || [];
    changedTouches = event.changedTouches || [];
    firstTouch = touches[0] || changedTouches[0] || {};
    canvasX = (event.pageX || firstTouch.pageX) - totalOffsetX;
    canvasY = (event.pageY || firstTouch.pageY) - totalOffsetY;
    if (x <= canvasX && canvasX <= x + width) {
      if (y <= canvasY && canvasY <= y + height) {
        return true;
      }
    }
    return false;
  };

  window.CanvasButton = (function() {
    function CanvasButton(canvas1, context, scaling, inactiveImg, activeImg, x1, y1, onEvent, offEvent) {
      var self;
      this.canvas = canvas1;
      this.context = context;
      this.scaling = scaling;
      this.inactiveImg = inactiveImg;
      this.activeImg = activeImg;
      this.x = x1;
      this.y = y1;
      this.onEvent = onEvent;
      this.offEvent = offEvent;
      this.currentImage = this.inactiveImg;
      this.width = this.inactiveImg.width * this.scaling;
      this.height = this.inactiveImg.height * this.scaling;
      this.trueX = this.x * this.scaling;
      this.trueY = this.y * this.scaling;
      self = this;
      this.mouseDownEvent = function(ev) {
        if (relMouseCoordsWithin(ev, self.canvas, self.trueX, self.trueY, self.width, self.height)) {
          return self.clicked();
        }
      };
      this.mouseUpEvent = function(ev) {
        if (relMouseCoordsWithin(ev, self.canvas, self.trueX, self.trueY, self.width, self.height)) {
          return self.released();
        } else {
          return self.globalMouseup();
        }
      };
      this.mouseDownEvent = _.throttle(this.mouseDownEvent, 100, {
        trailing: false
      });
      this.mouseUpEvent = _.throttle(this.mouseUpEvent, 100, {
        trailing: false
      });
      if (!isTouch()) {
        this.canvas.addEventListener('mousedown', this.mouseDownEvent);
        this.canvas.addEventListener('mouseup', this.mouseUpEvent);
      }
      this.canvas.addEventListener('touchstart', this.mouseDownEvent);
      this.canvas.addEventListener('touchend', this.mouseUpEvent);
    }

    CanvasButton.prototype.clicked = function() {};

    CanvasButton.prototype.released = function() {};

    CanvasButton.prototype.globalMouseup = function() {};

    CanvasButton.prototype.draw = function() {
      return this.context.drawImage(this.currentImage, this.x, this.y);
    };

    return CanvasButton;

  })();

  window.ToggleButton = (function(superClass) {
    extend(ToggleButton, superClass);

    function ToggleButton(canvas1, context, scaling, inactiveImg, activeImg, x1, y1, onEvent, offEvent) {
      this.canvas = canvas1;
      this.context = context;
      this.scaling = scaling;
      this.inactiveImg = inactiveImg;
      this.activeImg = activeImg;
      this.x = x1;
      this.y = y1;
      this.onEvent = onEvent;
      this.offEvent = offEvent;
      ToggleButton.__super__.constructor.call(this, this.canvas, this.context, this.scaling, this.inactiveImg, this.activeImg, this.x, this.y, this.onEvent, this.offEvent);
      this.isToggled = false;
    }

    ToggleButton.prototype.clicked = function() {
      this.isToggled = !this.isToggled;
      this.currentImage = this.isToggled ? this.activeImg : this.inactiveImg;
      if (this.isToggled) {
        return this.onEvent();
      } else {
        return this.offEvent();
      }
    };

    return ToggleButton;

  })(CanvasButton);

  window.ClickButton = (function(superClass) {
    extend(ClickButton, superClass);

    function ClickButton() {
      return ClickButton.__super__.constructor.apply(this, arguments);
    }

    ClickButton.prototype.clicked = function() {
      this.onEvent();
      this.currentImage = this.activeImg;
      return this.draw();
    };

    ClickButton.prototype.released = function() {
      this.offEvent();
      this.currentImage = this.inactiveImg;
      return this.draw();
    };

    ClickButton.prototype.globalMouseup = function() {
      this.currentImage = this.inactiveImg;
      return this.draw();
    };

    return ClickButton;

  })(CanvasButton);

}).call(this);
