// Generated by CoffeeScript 1.7.1
(function() {
  var imagePath, loadImage, loadTile;

  imagePath = "images/";

  loadImage = function(name) {
    var loadedImage;
    loadedImage = new Image();
    loadedImage.src = imagePath + name + ".png";
    return loadedImage;
  };

  loadTile = function(colorName) {
    return {
      up: loadImage("Tile" + colorName + "Up"),
      down: loadImage("Tile" + colorName + "Down")
    };
  };

  window.TritrisImage = {
    bg: loadImage("bg"),
    green: loadTile("Green"),
    red: loadTile("Red"),
    blue: loadTile("Blue"),
    orange: loadTile("Orange"),
    purple: loadTile("Purple"),
    yellow: loadTile("Yellow"),
    green: loadTile("Green"),
    bgTile: loadTile("Bg"),
    leftDir: loadImage("LeftDirIndicator"),
    rightDir: loadImage("RightDirIndicator")
  };

}).call(this);

//# sourceMappingURL=images.map
