// Generated by CoffeeScript 1.7.1
(function() {
  window.KeyBindings = {
    changeGravity: 90,
    left: 37,
    right: 39,
    down: 40,
    rotate: 38,
    flip: 88
  };

}).call(this);

//# sourceMappingURL=keybindings.map
